// Mocks generated by Mockito 5.4.6 from annotations
// in app_gobiernoti/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_gobiernoti/data/models/risk_model.dart' as _i6;
import 'package:app_gobiernoti/data/models/user_model.dart' as _i2;
import 'package:app_gobiernoti/data/services/auth_service.dart' as _i3;
import 'package:app_gobiernoti/data/services/biometric_service.dart' as _i8;
import 'package:app_gobiernoti/data/services/risk_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> loginWithEmail(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmail, [email, password]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#loginWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserModel> registerUser({
    required String? email,
    required String? password,
    required String? name,
    required String? role,
    String? dni,
    String? phone,
    String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #email: email,
              #password: password,
              #name: name,
              #role: role,
              #dni: dni,
              #phone: phone,
              #address: address,
            }),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#registerUser, [], {
                  #email: email,
                  #password: password,
                  #name: name,
                  #role: role,
                  #dni: dni,
                  #phone: phone,
                  #address: address,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<Map<String, dynamic>> enableBiometricForCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometricForCurrentUser, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> disableBiometricForCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometricForCurrentUser, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.UserModel?> loginWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithBiometrics, []),
            returnValue: _i4.Future<_i2.UserModel?>.value(),
          )
          as _i4.Future<_i2.UserModel?>);

  @override
  _i4.Future<bool> checkBiometricStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkBiometricStatus, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [RiskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiskService extends _i1.Mock implements _i5.RiskService {
  MockRiskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAiAnalysis(String? riskId, String? analysisText) =>
      (super.noSuchMethod(
            Invocation.method(#saveAiAnalysis, [riskId, analysisText]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Risk>> getRisks() =>
      (super.noSuchMethod(
            Invocation.method(#getRisks, []),
            returnValue: _i4.Future<List<_i6.Risk>>.value(<_i6.Risk>[]),
          )
          as _i4.Future<List<_i6.Risk>>);

  @override
  _i4.Future<void> addRisk(_i6.Risk? newRisk) =>
      (super.noSuchMethod(
            Invocation.method(#addRisk, [newRisk]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String generateNewId() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewId, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateNewId, []),
            ),
          )
          as String);

  @override
  _i4.Future<List<_i2.UserModel>> getAuditors() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditors, []),
            returnValue: _i4.Future<List<_i2.UserModel>>.value(
              <_i2.UserModel>[],
            ),
          )
          as _i4.Future<List<_i2.UserModel>>);

  @override
  _i4.Future<void> assignRiskToUser(String? riskId, _i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#assignRiskToUser, [riskId, user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateRiskStatus(
    String? riskId,
    _i6.RiskStatus? newStatus, {
    String? reviewNotes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRiskStatus,
              [riskId, newStatus],
              {#reviewNotes: reviewNotes},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i8.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#hasBiometrics, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> authenticate(String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [reason]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
