// Mocks generated by Mockito 5.4.6 from annotations
// in app_gobiernoti/test/presentation/providers/risk_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_gobiernoti/data/models/risk_model.dart' as _i4;
import 'package:app_gobiernoti/data/models/user_model.dart' as _i6;
import 'package:app_gobiernoti/data/services/risk_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RiskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiskService extends _i1.Mock implements _i2.RiskService {
  MockRiskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveAiAnalysis(String? riskId, String? analysisText) =>
      (super.noSuchMethod(
            Invocation.method(#saveAiAnalysis, [riskId, analysisText]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Risk>> getRisks() =>
      (super.noSuchMethod(
            Invocation.method(#getRisks, []),
            returnValue: _i3.Future<List<_i4.Risk>>.value(<_i4.Risk>[]),
          )
          as _i3.Future<List<_i4.Risk>>);

  @override
  _i3.Future<void> addRisk(_i4.Risk? newRisk) =>
      (super.noSuchMethod(
            Invocation.method(#addRisk, [newRisk]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String generateNewId() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewId, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateNewId, []),
            ),
          )
          as String);

  @override
  _i3.Future<List<_i6.UserModel>> getAuditors() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditors, []),
            returnValue: _i3.Future<List<_i6.UserModel>>.value(
              <_i6.UserModel>[],
            ),
          )
          as _i3.Future<List<_i6.UserModel>>);

  @override
  _i3.Future<void> assignRiskToUser(String? riskId, _i6.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#assignRiskToUser, [riskId, user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateRiskStatus(
    String? riskId,
    _i4.RiskStatus? newStatus, {
    String? reviewNotes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRiskStatus,
              [riskId, newStatus],
              {#reviewNotes: reviewNotes},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
